# ---------------------------------------------------------------
# Entrada
# ---------------------------------------------------------------
input type:keyboard {
    xkb_layout  br
    xkb_variant abnt2
    repeat_delay 300
    repeat_rate  35
}

input type:touchpad {
    tap enabled
    natural_scroll enabled
    dwt enabled
    middle_emulation enabled
    scroll_factor 0.6
}

focus_follows_mouse no
