# ---------------------------------------------------------------
# Entrada
# ---------------------------------------------------------------
input type:keyboard {
    xkb_layout  br
    xkb_model  abnt2
    repeat_delay 300
    repeat_rate  35
}

input type:touchpad {
    tap enabled
    natural_scroll enabled
    dwt enabled
    middle_emulation enabled
    scroll_factor 0.6
}

# Foco acompanha o mouse (sem precisar clicar)
focus_follows_mouse yes
