# ---------------------------------------------------------------
# Regras de janela
# ---------------------------------------------------------------
for_window [app_id="pavucontrol"]                floating enable, resize set 820 520
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable, resize set 820 520
for_window [app_id="blueman-manager"]            floating enable, resize set 720 480
for_window [app_id="nm-connection-editor"]       floating enable
for_window [app_id="nwg-displays"]               floating enable
for_window [app_id="nwg-look"]                   floating enable
for_window [app_id="org.gnome.Calculator"]       floating enable
for_window [app_id="swappy"]                     floating enable
for_window [app_id="solaar"]                     floating enable
for_window [app_id="firewall-config"]            floating enable
for_window [app_id="system-config-printer"]      floating enable
for_window [app_id="at.yrlf.wl_mirror"]          fullscreen enable
for_window [window_role="pop-up"]                floating enable
for_window [window_role="dialog"]                floating enable
for_window [window_type="dialog"]                floating enable
for_window [title="(?:Open|Save) (?:File|Folder|As)"] floating enable
for_window [title="^(Abrir|Salvar)"]             floating enable

# Indica apps rodando via XWayland no título (útil pra caçar borrão)
for_window [shell="xwayland"] title_format "%title [X]"

# Não deixa o swayidle apagar a tela durante vídeo/apresentação em tela cheia
for_window [app_id=".*"] inhibit_idle fullscreen
for_window [class=".*"]  inhibit_idle fullscreen
